### ISSUE TITLE
Treams installation failure due to NumPy 2.0.0 update

### ISSUE THREAD

**Issue by levdik** [tfp-photonics/treams#2]
`treams` fails to initialize when all the requirements are installed via pip automatically.

Here is how to recreate the bug. I'm using clean virtual environment on a Windows 11 machine, Python 3.10.2.
```
(venv) > pip install treams
```
```
Collecting treams
  Using cached treams-0.4.1-cp310-cp310-win_amd64.whl (1.6 MB)
Collecting numpy
  Using cached numpy-2.0.0-cp310-cp310-win_amd64.whl (16.5 MB)
Collecting scipy>=1.6
  Using cached scipy-1.14.0-cp310-cp310-win_amd64.whl (44.8 MB)
Installing collected packages: numpy, scipy, treams
Successfully installed numpy-2.0.0 scipy-1.14.0 treams-0.4.1
```
As the installation requirements don't specify a NumPy version, the newly released 2.0.0 is installed. This, however, leads to the following error in a Python script:
```python
>>> import treams
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\venv\lib\site-packages\treams\__init__.py", line 63, in <module>
    from treams._core import (  # noqa: F401
  File "...\venv\lib\site-packages\treams\_core.py", line 8, in <module>
    import treams._operators as op
  File "...\venv\lib\site-packages\treams\_operators.py", line 8, in <module>
    import treams.special as sc
  File "...\venv\lib\site-packages\treams\special\__init__.py", line 204, in <module>
    from treams.special import _gufuncs, _ufuncs  # noqa: F401
  File "src\\treams\\special\\_gufuncs.pyx", line 1, in init treams.special._gufuncs
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

This seems to be similar to [this issue in pandas](https://github.com/numpy/numpy/issues/26710) also caused by the latest NumPy major update. It's not clear for me why this issue occurs. A temporary fix might be adding `numpy<2.0.0` to the requirements.

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec

**Comment by jan-david-fischbach** [comment]
Hey @levdik, thanks for posting this here. We are working to fix the issue soon. It seems like numpy 2.0 has introduced some incompatibilities going beyond having to recompile the binaries against the new version. We'll likely publish a version to PyPi that pins an older numpy version this week. This will allow us to thoroughly investigate possible compatibility problems with numpy 2.0.
Best Regards
JD

**Comment by levdik** [comment]
@jan-david-fischbach thank you very much for the quick response and fix. Much appreciated.
