### ISSUE TITLE
BUG: Crash on import 

### ISSUE THREAD

**Issue by jan-david-fischbach** [tfp-photonics/treams#4]
[This change in scipy](https://github.com/scipy/scipy/commit/7d42c0abcea6506a1db5cd4f09d25ac9a338c257#diff-cdc6bc69dc59a741a5a099db3078d1ecbd569fe5840233ffd64d5e9f392c1010R6) leads to a crash at import time, when running a version of treams compiled with an incompatible version of scipy (before 1.14.1).

**Comment by jan-david-fischbach** [comment]
To summarize: 
 - `scipy` introduces a breaking change in `v1.14.1` where the input parameters for many scipy.cython_special functions was changed from `long` to `Py_ssize_t`
 - this makes the `treams` binaries compiled with a previous version of `scipy` incompatible to modern `scipy` and vice versa.
 - the newest versions of scipy do only support `python>=3.10`
 - As a consequence the only way forward, that I can see, is to drop support for `python<=3.9` and require `scipy>=1.14.1`, against which we then compile. This breaks **a lot** of compatibility with older versions of these dependencies, but I do not see another way (as far as I can see we cannot adaptively install a different binary depending on the version of `scipy`). 
- If a user wants to use `treams` with older versions of `python`/`scipy` they will have to resort to older versions of treams :/

**Comment by jan-david-fischbach** [comment]
## Revised Summary

After the release of `scipy` v1.14.1 has lead to a binary incompatibility to the precompiled `treams`. I have now established the following solution (in #5):

1. For python<=3.9 we continue to compile `treams` as before, as `scipy>=1.14.1` does not support these versions of python anyways.
2. For python>=3.10 we now compile against `scipy>=1.14.1` and also require `scipy>=1.14.1` for installation.

With this strategy we should cover all cases in which `treams` is newly installed.

## Problems:

If a user has previously installed treams and now updates scipy [^1] it will result in the following error at import time:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jd/bin/mambaforge/envs/treams-dev/lib/python3.10/site-packages/treams/__init__.py", line 63, in <module>
    from treams._core import (  # noqa: F401
  File "/home/jd/bin/mambaforge/envs/treams-dev/lib/python3.10/site-packages/treams/_core.py", line 8, in <module>
    import treams._operators as op
  File "/home/jd/bin/mambaforge/envs/treams-dev/lib/python3.10/site-packages/treams/_operators.py", line 8, in <module>
    import treams.special as sc
  File "/home/jd/bin/mambaforge/envs/treams-dev/lib/python3.10/site-packages/treams/special/__init__.py", line 204, in <module>
    from treams.special import _gufuncs, _ufuncs  # noqa: F401
  File "src/treams/special/_gufuncs.pyx", line 1, in init treams.special._gufuncs
    """Generalized universal functions for the special subpackage"""
  File "src/treams/special/_waves.pyx", line 1, in init treams.special._waves
    """Special mathematical functions related to waves"""
TypeError: C function scipy.special.cython_special.__pyx_fuse_0spherical_jn has wrong signature (expected __pyx_t_double_complex (long, __pyx_t_double_complex, int __pyx_skip_dispatch, struct __pyx_fuse_0__pyx_opt_args_5scipy_7special_14cython_special_spherical_jn *__pyx_optional_args), got __pyx_t_double_complex (Py_ssize_t, __pyx_t_double_complex, int __pyx_skip_dispatch, struct __pyx_fuse_0__pyx_opt_args_5scipy_7special_14cython_special_spherical_jn *__pyx_optional_args))
```

unfortunately I do not see any way around this.

**Comment by joakimpugesgaard** [comment]
I am still experiencing this issue when installing `treams` in a newly created `venv`. I am on macOS using python 3.11.13. 


As another closed thread has pointed out, installing `treams`-0.4.1 reinstalls `numpy` 2.2.6, resulting in the error upon 
`import treams`

`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

Installing treams while instead keeping numpy at version 1.25.2 instead results in the same error as this thread adresses:

`TypeError: C function scipy.special.cython_special.__pyx_fuse_0spherical_jn has wrong signature (expected __pyx_t_double_complex (long, __pyx_t_double_complex, int __pyx_skip_dispatch, struct __pyx_fuse_0__pyx_opt_args_5scipy_7special_14cython_special_spherical_jn *__pyx_optional_args), got __pyx_t_double_complex (Py_ssize_t, __pyx_t_double_complex, int __pyx_skip_dispatch, struct __pyx_fuse_0__pyx_opt_args_5scipy_7special_14cython_special_spherical_jn *__pyx_optional_args))`

This was tried with 
`pip install treams --no-deps` and `import treams`.

As far as I can tell, I am using the required packages and installing treams for the first time. What am I missing?

**Comment by jan-david-fischbach** [comment]
Hey @joakimpugesgaard,
there were some compatibility problems arising from the release of `numpy v2`. We recommend using the newest version of numpy with `treams v0.4.5`, which has been compiled against `numpy v2`. I am surprised, that v0.4.1 was installed for you.  `pip install --upgrade treams` should do the trick to get you up to v0.4.5. 

One last question: are you on an arm or intel mac? We have recently only tested `treams` on arm macs...

**Comment by joakimpugesgaard** [comment]
Thank you for your reply @jan-david-fischbach.
`pip install --upgrade treams` returns
`Requirement already satisfied: treams in ./newvenv3/lib/python3.12/site-packages (0.4.1)
Requirement already satisfied: numpy in ./newvenv3/lib/python3.12/site-packages (from treams) (2.3.1)
Requirement already satisfied: scipy>=1.6 in ./newvenv3/lib/python3.12/site-packages (from treams) (1.16.0)` 

I am on an intel mac, which could explain the issue, if it has not been tested there.

**Comment by jan-david-fischbach** [comment]
Hi, thanks for trying that out. So indeed the problem seems to be the Intel mac. For now can you quickly try out building `treams` from source? Step by step that would mean downloading this GitHub repository (as zip + extracting or by cloning). Then open a terminal in the root folder of the project and run `pip install -e .` (note the dot). If you use virtual environments (which I hope you do) make sure to use the corresponding `pip` executable, so that `treams` is installed into the desired environment. It should then compile the cython parts of treams on your machine, which might take a while. Let me know, if you can get it to work. Best Regards JD
